[package]
name = "leptos-accordion-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
console_error_panic_hook = "0.1.7"
accordion-rs = { path = "../../", features = ["lep"] }
leptos = { version = "0.7.2", features = ["csr"] }
wasm-logger = "0.2.0"
